# Site settings
title: Tech Festival 2019
author: the Tech Festival Team
email: techfestivalnyc@gmail.com
# this ">-" means to ignore newlines until "baseurl:"
description: >-
              Tech Festival is powered by
              a group of ambitious leaders.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username: techfestqc
facebook_username: techfestival19
instagram_username: techfestival19
linkedin_username: tech-festival

# Build settings
markdown: kramdown
